import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <nav className={styles.mainnav}>
        <ul>
          <Link href="/">
            
              <li>home</li>
            
          </Link>
          <Link href="/about">
            
              <li>about</li>
            
          </Link>
          <Link href="/blog">
            
              <li>blog</li>
            
          </Link>
          <Link href="/contact">
            
              <li>contact</li>
            
          </Link>
        </ul>
      </nav> */}
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>
        <img className={styles.myImg} src="/homeimg.jfif" width={237} height={158} alt="hunting coder" />

        <p>A blog for hunting coders by a hunting coder</p>
        <div className="blogs">
          <h2>popular blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2022?</h3>
            <p>JavaScript is the language used to design logic for the web.</p>
          </div>
        </div>
      </main>
    </div>
  );
}
